name: floor
description: >
  The typesafe, reactive, and lightweight SQLite abstraction for your Flutter applications.
  This library is the runtime dependency.
version: 1.4.2
homepage: https://pinchbv.github.io/floor/
repository: https://github.com/pinchbv/floor
issue_tracker: https://github.com/pinchbv/floor/issues
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  collection: ^1.15.0
  floor_annotation: ^1.4.2
  flutter:
    sdk: flutter
  meta: ^1.7.0
  path: ^1.8.1
  sqflite: ^2.0.0+4
  sqflite_common_ffi: ^2.0.0+3
  sqflite_common_ffi_web: ^0.4.2+2
  sqlparser: ^0.27.0

dev_dependencies:
  build_runner: ^2.1.2
  floor_generator: ^1.4.2
  flutter_test:
    sdk: flutter
  matcher: ^0.12.10
  mockito: ^5.0.15
  sqflite_common: ^2.4.4
